### ISSUE TITLE
crash after start

### ISSUE THREAD

**Issue by holgerimbery** [hobbyquaker/RedMatic-HomeKit#32]
Hello Sebastian,
first of all - RedMatic is developing magnificently and I really like the new web app and the HomeKit integration you started.
I know - this piece of software is beta and I read your warning more the once :-).

This morning - I gave RedMatic-Homekit a try and added the HomeMatic node, after deploying node red crashed with the following:
Oct 13 10:54:02 homematic-ccu2 daemon.info node-red[7363]: [redmatic-homekit-bridge:RedMatic Bridge] published bridge (33) RedMatic Bridge CC:22:3D:E3:CE:C8 on port 51826
Oct 13 10:54:05 homematic-ccu2 daemon.info node-red[7363]: [redmatic-homekit-bridge:RedMatic Bridge] published bridge (33) RedMatic Bridge CC:22:3D:E3:CE:C8 on port 51826
Oct 13 10:54:05 homematic-ccu2 daemon.err node-red: 13 Oct 10:54:05 - [red] Uncaught Exception:
Oct 13 10:54:05 homematic-ccu2 daemon.err node-red: 13 Oct 10:54:05 - Error: listen EADDRINUSE :::51826
Oct 13 10:54:05 homematic-ccu2 daemon.err node-red:     at Server.setupListenHandle [as _listen2] (net.js:1360:14)
Oct 13 10:54:05 homematic-ccu2 daemon.err node-red:     at listenInCluster (net.js:1401:12)
Oct 13 10:54:05 homematic-ccu2 daemon.err node-red:     at Server.listen (net.js:1485:7)
Oct 13 10:54:05 homematic-ccu2 daemon.err node-red:     at EventedHTTPServer.listen (/usr/local/addons/redmatic/var/node_modules/redmatic-homekit/node_modules/hap-nodejs/lib/util/eventedhttp.js:60:19)
Oct 13 10:54:05 homematic-ccu2 daemon.err node-red:     at HAPServer.listen (/usr/local/addons/redmatic/var/node_modules/redmatic-homekit/node_modules/hap-nodejs/lib/HAPServer.js:158:20)
Oct 13 10:54:05 homematic-ccu2 daemon.err node-red:     at Bridge.Accessory.publish (/usr/local/addons/redmatic/var/node_modules/redmatic-homekit/node_modules/hap-nodejs/lib/Accessory.js:607:16)
Oct 13 10:54:05 homematic-ccu2 daemon.err node-red:     at RedMaticHomeKitBridge.publishBridge (/usr/local/addons/redmatic/var/node_modules/redmatic-homekit/nodes/redmatic-homekit-bridge.js:78:25)
Oct 13 10:54:05 homematic-ccu2 daemon.err node-red:     at Timeout.waitForAccessoriesTimer.setTimeout [as _onTimeout] (/usr/local/addons/redmatic/var/node_modules/redmatic-homekit/nodes/redmatic-homekit-bridge.js:92:22)
Oct 13 10:54:05 homematic-ccu2 daemon.err node-red:     at ontimeout (timers.js:498:11)
Oct 13 10:54:05 homematic-ccu2 daemon.err node-red:     at tryOnTimeout (timers.js:323:5)
Oct 13 10:54:05 homematic-ccu2 daemon.err node-red:     at Timer.listOnTimeout (timers.js:290:5)

Any hint or should I just wait for an other release and stop my impatience *lol*

Holger

**Comment by hobbyquaker** [comment]
War das mit RedMatic 1.7.2? Hatte gehofft diesen Fehler bereits behoben zu haben :)
